@Api_HostAddress = http://localhost:5000


###

POST {{Api_HostAddress}}/tasks
Content-Type: application/json

{
  "name":"Study schoolwork",
  "isComplete":true
}

###
PATCH {{Api_HostAddress}}/todoitems/1
Content-Type: application/json

{
  "name":"read book"
}

###

GET {{Api_HostAddress}}/tasks

###
